"""Tests for the setup wizard's pure functions.

Only tests validate_phone, _escape_applescript, and generate_env — the
interactive prompts and AppleScript execution require a real macOS
environment and are not tested here.
"""

from apple_flow.setup_wizard import _escape_applescript, generate_env, validate_phone


# ---------------------------------------------------------------------------
# validate_phone
# ---------------------------------------------------------------------------


class TestValidatePhone:
    def test_valid_e164_us(self):
        assert validate_phone("+15551234567") == "+15551234567"

    def test_valid_e164_uk(self):
        assert validate_phone("+447911123456") == "+447911123456"

    def test_valid_e164_short(self):
        """Minimum 7 digits after +."""
        assert validate_phone("+1234567") == "+1234567"

    def test_valid_e164_long(self):
        """Maximum 15 digits after +."""
        assert validate_phone("+123456789012345") == "+123456789012345"

    def test_strips_whitespace(self):
        assert validate_phone("  +15551234567  ") == "+15551234567"

    def test_strips_leading_whitespace(self):
        assert validate_phone("  +15551234567") == "+15551234567"

    def test_rejects_no_plus(self):
        assert validate_phone("15551234567") is None

    def test_rejects_too_short(self):
        """Fewer than 7 digits after +."""
        assert validate_phone("+123456") is None

    def test_rejects_too_long(self):
        """More than 15 digits after +."""
        assert validate_phone("+1234567890123456") is None

    def test_rejects_letters(self):
        assert validate_phone("+1555ABC4567") is None

    def test_rejects_spaces_inside(self):
        assert validate_phone("+1 555 123 4567") is None

    def test_rejects_dashes(self):
        assert validate_phone("+1-555-123-4567") is None

    def test_rejects_empty(self):
        assert validate_phone("") is None

    def test_rejects_just_plus(self):
        assert validate_phone("+") is None


# ---------------------------------------------------------------------------
# _escape_applescript
# ---------------------------------------------------------------------------


class TestEscapeApplescript:
    def test_no_special_chars(self):
        assert _escape_applescript("agent-task") == "agent-task"

    def test_escapes_double_quotes(self):
        assert _escape_applescript('my "list"') == 'my \\"list\\"'

    def test_escapes_backslashes(self):
        assert _escape_applescript("path\\to\\thing") == "path\\\\to\\\\thing"

    def test_escapes_both(self):
        assert _escape_applescript('a\\"b') == 'a\\\\\\"b'

    def test_empty_string(self):
        assert _escape_applescript("") == ""

    def test_unicode_passthrough(self):
        assert _escape_applescript("taches") == "taches"


# ---------------------------------------------------------------------------
# generate_env
# ---------------------------------------------------------------------------


class TestGenerateEnv:
    def test_basic_no_gateways(self):
        result = generate_env(
            phone="+15551234567",
            connector="claude-cli",
            workspace="/Users/me/code",
            gateways=[],
        )
        assert "apple_flow_allowed_senders=+15551234567" in result
        assert "apple_flow_connector=claude-cli" in result
        assert "apple_flow_default_workspace=/Users/me/code" in result
        assert "apple_flow_allowed_workspaces=/Users/me/code" in result
        # No gateway sections
        assert "Apple Mail" not in result
        assert "Apple Reminders" not in result
        assert "Apple Notes" not in result
        assert "Apple Calendar" not in result

    def test_header_comment(self):
        result = generate_env("+15551234567", "claude-cli", "/tmp", [])
        assert result.startswith("# Generated by:")

    def test_all_gateways(self):
        result = generate_env(
            phone="+15551234567",
            connector="codex-cli",
            workspace="/Users/me/code",
            gateways=["mail", "reminders", "notes", "calendar"],
            mail_address="me@example.com",
        )
        assert "apple_flow_enable_mail_polling=true" in result
        assert "apple_flow_mail_allowed_senders=me@example.com" in result
        assert "apple_flow_mail_from_address=me@example.com" in result
        assert "apple_flow_enable_reminders_polling=true" in result
        assert "apple_flow_reminders_list_name=agent-task" in result
        assert "apple_flow_enable_notes_polling=true" in result
        assert "apple_flow_notes_folder_name=agent-task" in result
        assert "apple_flow_enable_calendar_polling=true" in result
        assert "apple_flow_calendar_name=agent-schedule" in result
        assert "apple_flow_connector=codex-cli" in result

    def test_single_gateway_mail(self):
        result = generate_env(
            phone="+15551234567",
            connector="claude-cli",
            workspace="/home/user",
            gateways=["mail"],
            mail_address="user@test.com",
        )
        assert "apple_flow_enable_mail_polling=true" in result
        assert "apple_flow_mail_allowed_senders=user@test.com" in result
        # Other gateways should not appear
        assert "apple_flow_enable_reminders_polling" not in result
        assert "apple_flow_enable_notes_polling" not in result
        assert "apple_flow_enable_calendar_polling" not in result

    def test_single_gateway_reminders(self):
        result = generate_env(
            phone="+15551234567",
            connector="claude-cli",
            workspace="/home/user",
            gateways=["reminders"],
        )
        assert "apple_flow_enable_reminders_polling=true" in result
        assert "apple_flow_enable_mail_polling" not in result

    def test_single_gateway_notes(self):
        result = generate_env(
            phone="+15551234567",
            connector="cline",
            workspace="/home/user",
            gateways=["notes"],
        )
        assert "apple_flow_enable_notes_polling=true" in result
        assert "apple_flow_connector=cline" in result
        assert "apple_flow_enable_mail_polling" not in result

    def test_single_gateway_calendar(self):
        result = generate_env(
            phone="+15551234567",
            connector="claude-cli",
            workspace="/home/user",
            gateways=["calendar"],
        )
        assert "apple_flow_enable_calendar_polling=true" in result
        assert "apple_flow_enable_mail_polling" not in result

    def test_owner_set_to_phone(self):
        result = generate_env(
            phone="+15559876543",
            connector="claude-cli",
            workspace="/tmp",
            gateways=["reminders", "notes", "calendar"],
        )
        assert "apple_flow_reminders_owner=+15559876543" in result
        assert "apple_flow_notes_owner=+15559876543" in result
        assert "apple_flow_calendar_owner=+15559876543" in result

    def test_safety_defaults_present(self):
        result = generate_env("+15551234567", "claude-cli", "/tmp", [])
        assert "apple_flow_only_poll_allowed_senders=true" in result
        assert "apple_flow_require_chat_prefix=false" in result
        assert "apple_flow_approval_ttl_minutes=20" in result
        assert "apple_flow_max_messages_per_minute=30" in result
